spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST}

  application:
    name: ${SPRING_APPLICATION_NAME}
  config:
    import: 'configserver:'
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI}
  session:
    store-type: redis
    timeout: 30m


  profiles:
    active: prod
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: ${SPRING_MAIL_HOST}
  security:
    jwt:
      secret: ${JWT_SECRET}
      expirationMs: 3600000
