spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  config:
    import: 'configserver:'
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI}
  session:
    store-type: redis
    timeout: 30m

  data:
    redis:
      host: ${REDIS_HOSTNAME}
      port: ${REDIS_PORT}

  profiles:
    active: prod
