name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - production
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      # Setup JDK or Node (depending on the app)
      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Run Unit Tests
        run: ./mvnw clean test # Adjust based on the build tool

      - name: Build Docker Image
        run: docker build -t your-service-name:${{ github.sha }} .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and Push Docker Image
        run: |
          docker tag your-service-name:${{ github.sha }} <your-ecr-url>:${{ github.sha }}
          docker push <your-ecr-url>:${{ github.sha }}

      - name: Deploy to AWS ECS (or update your ECS task)
        run: |
          aws ecs update-service --cluster your-ecs-cluster \
                                 --service your-ecs-service \
                                 --force-new-deployment
