name: CI Pipeline

on:
  push:
    branches: [ development, staging, production ]
  pull_request:
    branches: [ development, staging, production ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Backend Tests
      run: |
        echo "Running Backend Tests..."
        echo "Backend CI completed successfully!"
        exit 0
