name: Allure & Coverage Report CI

on:
  push:
    branches:
      - development
      - staging
  pull_request:
    branches:
      - development
      - staging

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download external pom.xml
        run: |
          curl -o external-pom.xml https://raw.githubusercontent.com/AmaliTech-Training-Academy/talentradar-qa-rw/refs/heads/report-coverage/external-pom.xml

      - name: Download allure.properties into resources
        run: |
          mkdir -p src/test/resources
          curl -o src/test/resources/allure.properties https://raw.githubusercontent.com/AmaliTech-Training-Academy/talentradar-qa-rw/refs/heads/report-coverage/allure.properties

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run tests and generate coverage
        run: mvn clean verify -f external-pom.xml
        continue-on-error: true

      - name: Upload coverage report
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: target/site/jacoco/jacoco.xml

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: target/allure-results/
          retention-days: 3

  generate-allure-report:
    runs-on: ubuntu-latest
    needs: test-coverage
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download results
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: allure-results
          path: allure-results/

      - name: Get Allure history
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 1

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          force_orphan: true
